FINANCIALS_COLUMNS = [
    "ticker",
    "insert_date",
    "report_date",
    "currency_code",
    "frequency",
    "Tax Effect Of Unusual Items",
    "Tax Rate For Calcs",
    "Normalized EBITDA",
    "Net Income From Continuing Operation Net Minority Interest",
    "Reconciled Depreciation",
    "Reconciled Cost Of Revenue",
    "EBIT",
    "Net Interest Income",
    "Interest Expense",
    "Interest Income",
    "Normalized Income",
    "Net Income From Continuing And Discontinued Operation",
    "Total Expenses",
    "Total Operating Income As Reported",
    "Diluted Average Shares",
    "Basic Average Shares",
    "Diluted EPS",
    "Basic EPS",
    "Diluted NI Availto Com Stockholders",
    "Net Income Common Stockholders",
    "Net Income",
    "Net Income Including Noncontrolling Interests",
    "Net Income Continuous Operations",
    "Tax Provision",
    "Pretax Income",
    "Other Income Expense",
    "Other Non Operating Income Expenses",
    "Net Non Operating Interest Income Expense",
    "Interest Expense Non Operating",
    "Interest Income Non Operating",
    "Operating Income",
    "Operating Expense",
    "Research And Development",
    "Selling General And Administration",
    "Gross Profit",
    "Cost Of Revenue",
    "Total Revenue",
    "Operating Revenue",
]

CASH_FLOW_COLUMNS = [
    "ticker",
    "insert_date",
    "report_date",
    "currency_code",
    "frequency",
    "Free Cash Flow",
    "Repurchase Of Capital Stock",
    "Repayment Of Debt",
    "Issuance Of Debt",
    "Issuance Of Capital Stock",
    "Capital Expenditure",
    "Interest Paid Supplemental Data",
    "Income Tax Paid Supplemental Data",
    "End Cash Position",
    "Beginning Cash Position",
    "Changes In Cash",
    "Financing Cash Flow",
    "Cash Flow From Continuing Financing Activities",
    "Net Other Financing Charges",
    "Cash Dividends Paid",
    "Common Stock Dividend Paid",
    "Net Common Stock Issuance",
    "Common Stock Payments",
    "Common Stock Issuance",
    "Net Issuance Payments Of Debt",
    "Net Short Term Debt Issuance",
    "Short Term Debt Payments",
    "Short Term Debt Issuance",
    "Net Long Term Debt Issuance",
    "Long Term Debt Payments",
    "Long Term Debt Issuance",
    "Investing Cash Flow",
    "Cash Flow From Continuing Investing Activities",
    "Net Other Investing Changes",
    "Net Investment Purchase And Sale",
    "Sale Of Investment",
    "Purchase Of Investment",
    "Net Business Purchase And Sale",
    "Purchase Of Business",
    "Net PPE Purchase And Sale",
    "Purchase Of PPE",
    "Operating Cash Flow",
    "Cash Flow From Continuing Operating Activities",
    "Change In Working Capital",
    "Change In Other Working Capital",
    "Change In Other Current Liabilities",
    "Change In Other Current Assets",
    "Change In Payables And Accrued Expense",
    "Change In Payable",
    "Change In Account Payable",
    "Change In Inventory",
    "Change In Receivables",
    "Changes In Account Receivables",
    "Other Non Cash Items",
    "Stock Based Compensation",
    "Deferred Tax",
    "Deferred Income Tax",
    "Depreciation Amortization Depletion",
    "Depreciation And Amortization",
    "Net Income From Continuing Operations",
]

BALANCE_SHEET_COLUMNS = [
    "ticker",
    "insert_date",
    "report_date",
    "Ordinary Shares Number",
    "Share Issued",
    "Net Debt",
    "Total Debt",
    "Tangible Book Value",
    "Invested Capital",
    "Working Capital",
    "Net Tangible Assets",
    "Common Stock Equity",
    "Total Capitalization",
    "Total Equity Gross Minority Interest",
    "Stockholders Equity",
    "Gains Losses Not Affecting Retained Earnings",
    "Retained Earnings",
    "Capital Stock",
    "Common Stock",
    "Total Liabilities Net Minority Interest",
    "Total Non Current Liabilities Net Minority Interest",
    "Other Non Current Liabilities",
    "Tradeand Other Payables Non Current",
    "Long Term Debt And Capital Lease Obligation",
    "Long Term Debt",
    "Current Liabilities",
    "Other Current Liabilities",
    "Current Deferred Liabilities",
    "Current Deferred Revenue",
    "Current Debt And Capital Lease Obligation",
    "Current Debt",
    "Other Current Borrowings",
    "Commercial Paper",
    "Payables And Accrued Expenses",
    "Payables",
    "Accounts Payable",
    "Total Assets",
    "Total Non Current Assets",
    "Other Non Current Assets",
    "Investments And Advances",
    "Other Investments",
    "Investmentin Financial Assets",
    "Available For Sale Securities",
    "Net PPE",
    "Accumulated Depreciation",
    "Gross PPE",
    "Leases",
    "Machinery Furniture Equipment",
    "Land And Improvements",
    "Properties",
    "Current Assets",
    "Other Current Assets",
    "Inventory",
    "Receivables",
    "Other Receivables",
    "Accounts Receivable",
    "Cash Cash Equivalents And Short Term Investments",
    "Other Short Term Investments",
    "Cash And Cash Equivalents",
    "Cash Equivalents",
    "Cash Financial",
]

INCOME_STMT_COLUMNS = [
    "ticker",
    "insert_date",
    "report_date",
    "currency_code",
    "frequency",
    "tax_effect_of_unusual_items",
    "tax_rate_for_calcs",
    "normalized_ebitda",
    "net_income_from_continuing_operation_net_minority_interest",
    "reconciled_depreciation",
    "reconciled_cost_of_revenue",
    "ebit",
    "net_interest_income",
    "interest_expense",
    "interest_income",
    "normalized_income",
    "net_income_from_continuing_and_discontinued_operation",
    "total_expenses",
    "total_operating_income_as_reported",
    "diluted_ni_availto_com_stockholders",
    "net_income_common_stockholders",
    "net_income",
    "net_income_including_noncontrolling_interests",
    "net_income_continuous_operations",
    "tax_provision",
    "pretax_income",
    "other_income_expense",
    "other_non_operating_income_expenses",
    "net_non_operating_interest_income_expense",
    "interest_expense_non_operating",
    "interest_income_non_operating",
    "operating_income",
    "operating_expense",
    "research_and_development",
    "selling_general_and_administration",
    "gross_profit",
    "cost_of_revenue",
    "total_revenue",
    "operating_revenue",
    "diluted_average_shares",
    "basic_average_shares",
    "total_unusual_items",
    "total_unusual_items_excluding_goodwill",
    "diluted_eps",
    "basic_eps",
    "minority_interests",
    "special_income_charges",
    "gain_on_sale_of_ppe",
    "restructuring_and_merger_and_acquisition",
    "earnings_from_equity_interest",
    "gain_on_sale_of_security",
    "other_operating_expenses",
    "restructuring_and_mergern_acquisition",
    "preferred_stock_dividends",
    "net_income_discontinuous_operations",
    "impairment_of_capital_assets",
    "depreciation_amortization_depletion_income_statement",
    "depreciation_and_amortization_in_income_statement",
    "average_dilution_earnings",
    "otherunder_preferred_stock_dividend",
    "selling_and_marketing_expense",
    "general_and_administrative_expense",
    "other_special_charges",
    "write_off",
    "total_other_finance_cost",
    "amortization",
    "amortization_of_intangibles_income_statement",
    "other_gand_a",
    "salaries_and_wages",
    "excise_taxes",
]
