FINANCIALS_COLUMNS = [
    "ticker",
    "insert_date",
    "report_date",
    "currency_code",
    "frequency",
    "Tax Effect Of Unusual Items",
    "Tax Rate For Calcs",
    "Normalized EBITDA",
    "Net Income From Continuing Operation Net Minority Interest",
    "Reconciled Depreciation",
    "Reconciled Cost Of Revenue",
    "EBIT",
    "Net Interest Income",
    "Interest Expense",
    "Interest Income",
    "Normalized Income",
    "Net Income From Continuing And Discontinued Operation",
    "Total Expenses",
    "Total Operating Income As Reported",
    "Diluted Average Shares",
    "Basic Average Shares",
    "Diluted EPS",
    "Basic EPS",
    "Diluted NI Availto Com Stockholders",
    "Net Income Common Stockholders",
    "Net Income",
    "Net Income Including Noncontrolling Interests",
    "Net Income Continuous Operations",
    "Tax Provision",
    "Pretax Income",
    "Other Income Expense",
    "Other Non Operating Income Expenses",
    "Net Non Operating Interest Income Expense",
    "Interest Expense Non Operating",
    "Interest Income Non Operating",
    "Operating Income",
    "Operating Expense",
    "Research And Development",
    "Selling General And Administration",
    "Gross Profit",
    "Cost Of Revenue",
    "Total Revenue",
    "Operating Revenue",
]

CASH_FLOW_COLUMNS = [
    "ticker",
    "insert_date",
    "report_date",
    "currency_code",
    "frequency",
    "Free Cash Flow",
	"Repurchase Of Capital Stock",
	"Repayment Of Debt",
	"Issuance Of Debt",
	"Issuance Of Capital Stock",
	"Capital Expenditure",
	"Interest Paid Supplemental Data",
	"Income Tax Paid Supplemental Data",
	"End Cash Position",
	"Beginning Cash Position",
	"Changes In Cash",
	"Financing Cash Flow",
	"Cash Flow From Continuing Financing Activities",
	"Net Other Financing Charges",
	"Cash Dividends Paid",
	"Common Stock Dividend Paid",
	"Net Common Stock Issuance",
	"Common Stock Payments",
	"Common Stock Issuance",
	"Net Issuance Payments Of Debt",
	"Net Short Term Debt Issuance",
	"Short Term Debt Payments",
	"Short Term Debt Issuance",
	"Net Long Term Debt Issuance",
	"Long Term Debt Payments",
	"Long Term Debt Issuance",
	"Investing Cash Flow",
	"Cash Flow From Continuing Investing Activities",
	"Net Other Investing Changes",
	"Net Investment Purchase And Sale",
	"Sale Of Investment",
	"Purchase Of Investment",
	"Net Business Purchase And Sale",
	"Purchase Of Business",
	"Net PPE Purchase And Sale",
	"Purchase Of PPE",
	"Operating Cash Flow",
	"Cash Flow From Continuing Operating Activities",
	"Change In Working Capital",
	"Change In Other Working Capital",
	"Change In Other Current Liabilities",
	"Change In Other Current Assets",
	"Change In Payables And Accrued Expense",
	"Change In Payable",
	"Change In Account Payable",
	"Change In Inventory",
	"Change In Receivables",
	"Changes In Account Receivables",
	"Other Non Cash Items",
	"Stock Based Compensation",
	"Deferred Tax",
	"Deferred Income Tax",
	"Depreciation Amortization Depletion",
	"Depreciation And Amortization",
	"Net Income From Continuing Operations",
]