CREATE SCHEMA IF NOT EXISTS stocks;

CREATE TABLE IF NOT EXISTS stocks.tickers_list (
    ticker varchar(10) NOT NULL PRIMARY KEY,
    name varchar(100),
    exchange varchar(10),
    category_name varchar(100),
    country varchar(100)
);

CREATE TABLE IF NOT EXISTS stocks.valid_tickers (
    ticker varchar(10) NOT NULL PRIMARY KEY,
    date date NOT NULL DEFAULT now(),
    currency_code varchar(10),
    market_cap bigint,
    total_revenue bigint,
    free_cash_flow bigint,
    total_assets bigint,
    validity boolean NOT NULL
);

CREATE TABLE stocks.financials (
    ticker varchar(100) NOT NULL,
    insert_date date NOT NULL DEFAULT now(),
    report_date date NOT NULL,
    currency_code varchar(10) NULL,
    frequency varchar(10) NULL,
    "Tax Effect Of Unusual Items" float8 NULL,
    "Tax Rate For Calcs" float8 NULL,
    "Normalized EBITDA" float8 NULL,
    "Net Income From Continuing Operation Net Minority Interest" float8 NULL,
    "Reconciled Depreciation" float8 NULL,
    "Reconciled Cost Of Revenue" float8 NULL,
    "EBIT" float8 NULL,
    "Net Interest Income" float8 NULL,
    "Interest Expense" float8 NULL,
    "Interest Income" float8 NULL,
    "Normalized Income" float8 NULL,
    "Net Income From Continuing And Discontinued Operation" float8 NULL,
    "Total Expenses" float8 NULL,
    "Total Operating Income As Reported" float8 NULL,
    "Diluted Average Shares" float8 NULL,
    "Basic Average Shares" float8 NULL,
    "Diluted EPS" float8 NULL,
    "Basic EPS" float8 NULL,
    "Diluted NI Availto Com Stockholders" float8 NULL,
    "Net Income Common Stockholders" float8 NULL,
    "Net Income" float8 NULL,
    "Net Income Including Noncontrolling Interests" float8 NULL,
    "Net Income Continuous Operations" float8 NULL,
    "Tax Provision" float8 NULL,
    "Pretax Income" float8 NULL,
    "Other Income Expense" float8 NULL,
    "Other Non Operating Income Expenses" float8 NULL,
    "Net Non Operating Interest Income Expense" float8 NULL,
    "Interest Expense Non Operating" float8 NULL,
    "Interest Income Non Operating" float8 NULL,
    "Operating Income" float8 NULL,
    "Operating Expense" float8 NULL,
    "Research And Development" float8 NULL,
    "Selling General And Administration" float8 NULL,
    "Gross Profit" float8 NULL,
    "Cost Of Revenue" float8 NULL,
    "Total Revenue" float8 NULL,
    "Operating Revenue" float8 NULL,
    CONSTRAINT financials_pkey PRIMARY KEY (ticker, report_date)
);

CREATE TABLE stocks.cash_flow (
    ticker varchar(100) NOT NULL,
    insert_date date NOT NULL DEFAULT now(),
    report_date date NOT NULL,
    "Free Cash Flow" float8 NULL,
    "Repurchase Of Capital Stock" float8 NULL,
    "Repayment Of Debt" float8 NULL,
    "Issuance Of Debt" float8 NULL,
    "Issuance Of Capital Stock" float8 NULL,
    "Capital Expenditure" float8 NULL,
    "Interest Paid Supplemental Data" float8 NULL,
    "Income Tax Paid Supplemental Data" float8 NULL,
    "End Cash Position" float8 NULL,
    "Beginning Cash Position" float8 NULL,
    "Changes In Cash" float8 NULL,
    "Financing Cash Flow" float8 NULL,
    "Cash Flow From Continuing Financing Activities" float8 NULL,
    "Net Other Financing Charges" float8 NULL,
    "Cash Dividends Paid" float8 NULL,
    "Common Stock Dividend Paid" float8 NULL,
    "Net Common Stock Issuance" float8 NULL,
    "Common Stock Payments" float8 NULL,
    "Common Stock Issuance" float8 NULL,
    "Net Issuance Payments Of Debt" float8 NULL,
    "Net Short Term Debt Issuance" float8 NULL,
    "Short Term Debt Payments" float8 NULL,
    "Short Term Debt Issuance" float8 NULL,
    "Net Long Term Debt Issuance" float8 NULL,
    "Long Term Debt Payments" float8 NULL,
    "Long Term Debt Issuance" float8 NULL,
    "Investing Cash Flow" float8 NULL,
    "Cash Flow From Continuing Investing Activities" float8 NULL,
    "Net Other Investing Changes" float8 NULL,
    "Net Investment Purchase And Sale" float8 NULL,
    "Sale Of Investment" float8 NULL,
    "Purchase Of Investment" float8 NULL,
    "Net Business Purchase And Sale" float8 NULL,
    "Purchase Of Business" float8 NULL,
    "Net PPE Purchase And Sale" float8 NULL,
    "Purchase Of PPE" float8 NULL,
    "Operating Cash Flow" float8 NULL,
    "Cash Flow From Continuing Operating Activities" float8 NULL,
    "Change In Working Capital" float8 NULL,
    "Change In Other Working Capital" float8 NULL,
    "Change In Other Current Liabilities" float8 NULL,
    "Change In Other Current Assets" float8 NULL,
    "Change In Payables And Accrued Expense" float8 NULL,
    "Change In Payable" float8 NULL,
    "Change In Account Payable" float8 NULL,
    "Change In Inventory" float8 NULL,
    "Change In Receivables" float8 NULL,
    "Changes In Account Receivables" float8 NULL,
    "Other Non Cash Items" float8 NULL,
    "Stock Based Compensation" float8 NULL,
    "Deferred Tax" float8 NULL,
    "Deferred Income Tax" float8 NULL,
    "Depreciation Amortization Depletion" float8 NULL,
    "Depreciation And Amortization" float8 NULL,
    "Net Income From Continuing Operations" float8 NULL,
    currency_code varchar(10) NULL,
    frequency varchar(10) NULL,
    CONSTRAINT cash_flow_pkey PRIMARY KEY (ticker, report_date)
);

CREATE TABLE stocks.balance_sheet (
    ticker varchar(100) NOT NULL,
    insert_date date NOT NULL DEFAULT now(),
    report_date date NOT NULL,
    currency_code varchar(10) NULL,
    frequency varchar(10) NULL,
    "Ordinary Shares Number" float8 NULL,
    "Share Issued" float8 NULL,
    "Net Debt" float8 NULL,
    "Total Debt" float8 NULL,
    "Tangible Book Value" float8 NULL,
    "Invested Capital" float8 NULL,
    "Working Capital" float8 NULL,
    "Net Tangible Assets" float8 NULL,
    "Common Stock Equity" float8 NULL,
    "Total Capitalization" float8 NULL,
    "Total Equity Gross Minority Interest" float8 NULL,
    "Stockholders Equity" float8 NULL,
    "Gains Losses Not Affecting Retained Earnings" float8 NULL,
    "Retained Earnings" float8 NULL,
    "Capital Stock" float8 NULL,
    "Common Stock" float8 NULL,
    "Total Liabilities Net Minority Interest" float8 NULL,
    "Total Non Current Liabilities Net Minority Interest" float8 NULL,
    "Other Non Current Liabilities" float8 NULL,
    "Tradeand Other Payables Non Current" float8 NULL,
    "Long Term Debt And Capital Lease Obligation" float8 NULL,
    "Long Term Debt" float8 NULL,
    "Current Liabilities" float8 NULL,
    "Other Current Liabilities" float8 NULL,
    "Current Deferred Liabilities" float8 NULL,
    "Current Deferred Revenue" float8 NULL,
    "Current Debt And Capital Lease Obligation" float8 NULL,
    "Current Debt" float8 NULL,
    "Other Current Borrowings" float8 NULL,
    "Commercial Paper" float8 NULL,
    "Payables And Accrued Expenses" float8 NULL,
    "Payables" float8 NULL,
    "Accounts Payable" float8 NULL,
    "Total Assets" float8 NULL,
    "Total Non Current Assets" float8 NULL,
    "Other Non Current Assets" float8 NULL,
    "Investments And Advances" float8 NULL,
    "Other Investments" float8 NULL,
    "Investmentin Financial Assets" float8 NULL,
    "Available For Sale Securities" float8 NULL,
    "Net PPE" float8 NULL,
    "Accumulated Depreciation" float8 NULL,
    "Gross PPE" float8 NULL,
    "Leases" float8 NULL,
    "Machinery Furniture Equipment" float8 NULL,
    "Land And Improvements" float8 NULL,
    "Properties" float8 NULL,
    "Current Assets" float8 NULL,
    "Other Current Assets" float8 NULL,
    "Inventory" float8 NULL,
    "Receivables" float8 NULL,
    "Other Receivables" float8 NULL,
    "Accounts Receivable" float8 NULL,
    "Cash Cash Equivalents And Short Term Investments" float8 NULL,
    "Other Short Term Investments" float8 NULL,
    "Cash And Cash Equivalents" float8 NULL,
    "Cash Equivalents" float8 NULL,
    "Cash Financial" float8 NULL,
    CONSTRAINT balance_sheet_pkey PRIMARY KEY (ticker, report_date)
);

CREATE TABLE stocks.income_stmt (
    ticker varchar(100) NOT NULL,
    insert_date date NOT NULL DEFAULT now(),
    report_date date NOT NULL,
    currency_code varchar(10) NULL,
    frequency varchar(10) NULL,
    tax_effect_of_unusual_items DECIMAL,
    tax_rate_for_calcs DECIMAL,
    normalized_ebitda DECIMAL,
    net_income_from_continuing_operation_net_minority_interest DECIMAL,
    reconciled_depreciation DECIMAL,
    reconciled_cost_of_revenue DECIMAL,
    ebit DECIMAL,
    net_interest_income DECIMAL,
    interest_expense DECIMAL,
    interest_income DECIMAL,
    normalized_income DECIMAL,
    net_income_from_continuing_and_discontinued_operation DECIMAL,
    total_expenses DECIMAL,
    total_operating_income_as_reported DECIMAL,
    diluted_ni_availto_com_stockholders DECIMAL,
    net_income_common_stockholders DECIMAL,
    net_income DECIMAL,
    net_income_including_noncontrolling_interests DECIMAL,
    net_income_continuous_operations DECIMAL,
    tax_provision DECIMAL,
    pretax_income DECIMAL,
    other_income_expense DECIMAL,
    other_non_operating_income_expenses DECIMAL,
    net_non_operating_interest_income_expense DECIMAL,
    interest_expense_non_operating DECIMAL,
    interest_income_non_operating DECIMAL,
    operating_income DECIMAL,
    operating_expense DECIMAL,
    research_and_development DECIMAL,
    selling_general_and_administration DECIMAL,
    gross_profit DECIMAL,
    cost_of_revenue DECIMAL,
    total_revenue DECIMAL,
    operating_revenue DECIMAL,
    CONSTRAINT income_sttm_pkey PRIMARY KEY (ticker, report_date)
);
