CREATE SCHEMA IF NOT EXISTS stocks;

CREATE TABLE IF NOT EXISTS stocks.tickers_list (
    ticker varchar(10) NOT NULL PRIMARY KEY,
    name varchar(100),
    exchange varchar(10),
    category_name varchar(100),
    country varchar(100)
);

CREATE TABLE IF NOT EXISTS stocks.valid_tickers (
    ticker varchar(10) NOT NULL PRIMARY KEY,
    date date NOT NULL DEFAULT now(),
    currency_code varchar(10),
    market_cap bigint,
    total_revenue bigint,
    free_cash_flow bigint,
    total_assets bigint,
    validity boolean NOT NULL
);


CREATE TABLE stocks.balance_sheet (
    ticker varchar(100) NOT NULL,
    insert_date date NOT NULL DEFAULT now(),
    report_date date NOT NULL,
    currency_code varchar(10) NULL,
    frequency varchar(10) NULL,
    ordinary_shares_number float NULL,
    share_issued float NULL,
    net_debt float NULL,
    total_debt float NULL,
    tangible_book_value float NULL,
    invested_capital float NULL,
    working_capital float NULL,
    net_tangible_assets float NULL,
    common_stock_equity float NULL,
    total_capitalization float NULL,
    total_equity_gross_minority_interest float NULL,
    stockholders_equity float NULL,
    gains_losses_not_affecting_retained_earnings float NULL,
    other_equity_adjustments float NULL,
    retained_earnings float NULL,
    capital_stock float NULL,
    common_stock float NULL,
    total_liabilities_net_minority_interest float NULL,
    total_non_current_liabilities_net_minority_interest float NULL,
    other_non_current_liabilities float NULL,
    tradeand_other_payables_non_current float NULL,
    long_term_debt_and_capital_lease_obligation float NULL,
    long_term_debt float NULL,
    current_liabilities float NULL,
    other_current_liabilities float NULL,
    current_deferred_liabilities float NULL,
    current_deferred_revenue float NULL,
    current_debt_and_capital_lease_obligation float NULL,
    current_debt float NULL,
    other_current_borrowings float NULL,
    commercial_paper float NULL,
    payables_and_accrued_expenses float NULL,
    payables float NULL,
    accounts_payable float NULL,
    total_assets float NULL,
    total_non_current_assets float NULL,
    other_non_current_assets float NULL,
    investments_and_advances float NULL,
    other_investments float NULL,
    investmentin_financial_assets float NULL,
    available_for_sale_securities float NULL,
    net_ppe float NULL,
    accumulated_depreciation float NULL,
    gross_ppe float NULL,
    leases float NULL,
    machinery_furniture_equipment float NULL,
    land_and_improvements float NULL,
    properties float NULL,
    current_assets float NULL,
    other_current_assets float NULL,
    inventory float NULL,
    finished_goods float NULL,
    raw_materials float NULL,
    receivables float NULL,
    other_receivables float NULL,
    accounts_receivable float NULL,
    cash_cash_equivalents_and_short_term_investments float NULL,
    other_short_term_investments float NULL,
    cash_and_cash_equivalents float NULL,
    cash_equivalents float NULL,
    cash_financial float NULL,
    CONSTRAINT balance_sheet_pkey PRIMARY KEY (ticker, report_date, frequency)
);

CREATE TABLE stocks.income_stmt (
    ticker varchar(100) NOT NULL,
    insert_date date NOT NULL DEFAULT now(),
    report_date date NOT NULL,
    currency_code varchar(10) NULL,
    frequency varchar(10) NULL,
    tax_effect_of_unusual_items float NULL,
    tax_rate_for_calcs float NULL,
    normalized_ebitda float NULL,
    net_income_from_continuing_operation_net_minority_interest float NULL,
    reconciled_depreciation float NULL,
    reconciled_cost_of_revenue float NULL,
    ebit float NULL,
    net_interest_income float NULL,
    interest_expense float NULL,
    interest_income float NULL,
    normalized_income float NULL,
    net_income_from_continuing_and_discontinued_operation float NULL,
    total_expenses float NULL,
    total_operating_income_as_reported float NULL,
    diluted_ni_availto_com_stockholders float NULL,
    net_income_common_stockholders float NULL,
    net_income float NULL,
    net_income_including_noncontrolling_interests float NULL,
    net_income_continuous_operations float NULL,
    tax_provision float NULL,
    pretax_income float NULL,
    other_income_expense float NULL,
    other_non_operating_income_expenses float NULL,
    net_non_operating_interest_income_expense float NULL,
    interest_expense_non_operating float NULL,
    interest_income_non_operating float NULL,
    operating_income float NULL,
    operating_expense float NULL,
    research_and_development float NULL,
    selling_general_and_administration float NULL,
    gross_profit float NULL,
    cost_of_revenue float NULL,
    total_revenue float NULL,
    operating_revenue float NULL,
    diluted_average_shares float NULL,
    basic_average_shares float NULL,
    total_unusual_items float NULL,
    total_unusual_items_excluding_goodwill float NULL,
    diluted_eps float NULL,
    basic_eps float NULL,
    minority_interests float NULL,
    special_income_charges float NULL,
    gain_on_sale_of_ppe float NULL,
    restructuring_and_merger_and_acquisition float NULL,
    earnings_from_equity_interest float NULL,
    gain_on_sale_of_security float NULL,
    other_operating_expenses float NULL,
    restructuring_and_mergern_acquisition float NULL,
    average_dilution_earnings float NULL,
    preferred_stock_dividends float NULL,
    net_income_discontinuous_operations float NULL,
    impairment_of_capital_assets float NULL,
    depreciation_amortization_depletion_income_statement float NULL,
    depreciation_and_amortization_in_income_statement float NULL,
    otherunder_preferred_stock_dividend float NULL,
    selling_and_marketing_expense float NULL,
    general_and_administrative_expense float NULL,
    other_special_charges float NULL,
    write_off float NULL,
    total_other_finance_cost float NULL,
    amortization float NULL,
    amortization_of_intangibles_income_statement float NULL,
    other_gand_a float NULL,
    salaries_and_wages float NULL,
    excise_taxes float NULL,
    CONSTRAINT income_stmt_pkey PRIMARY KEY (ticker, report_date, frequency)
);

CREATE TABLE stocks.cashflow (
    ticker varchar(100) NOT NULL,
    insert_date date NOT NULL DEFAULT now(),
    report_date date NOT NULL,
    currency_code varchar(10) NULL,
    frequency varchar(10) NULL,
    free_cash_flow float NULL,
    repurchase_of_capital_stock float NULL,
    repayment_of_debt float NULL,
    issuance_of_debt float NULL,
    issuance_of_capital_stock float NULL,
    capital_expenditure float NULL,
    interest_paid_supplemental_data float NULL,
    income_tax_paid_supplemental_data float NULL,
    end_cash_position float NULL,
    beginning_cash_position float NULL,
    changes_in_cash float NULL,
    financing_cash_flow float NULL,
    cash_flow_from_continuing_financing_activities float NULL,
    net_other_financing_charges float NULL,
    cash_dividends_paid float NULL,
    common_stock_dividend_paid float NULL,
    net_common_stock_issuance float NULL,
    common_stock_payments float NULL,
    common_stock_issuance float NULL,
    net_issuance_payments_of_debt float NULL,
    net_short_term_debt_issuance float NULL,
    short_term_debt_payments float NULL,
    short_term_debt_issuance float NULL,
    net_long_term_debt_issuance float NULL,
    long_term_debt_payments float NULL,
    long_term_debt_issuance float NULL,
    investing_cash_flow float NULL,
    cash_flow_from_continuing_investing_activities float NULL,
    net_other_investing_changes float NULL,
    net_investment_purchase_and_sale float NULL,
    sale_of_investment float NULL,
    purchase_of_investment float NULL,
    net_business_purchase_and_sale float NULL,
    purchase_of_business float NULL,
    net_ppe_purchase_and_sale float NULL,
    purchase_of_ppe float NULL,
    operating_cash_flow float NULL,
    cash_flow_from_continuing_operating_activities float NULL,
    change_in_working_capital float NULL,
    change_in_other_working_capital float NULL,
    change_in_other_current_liabilities float NULL,
    change_in_other_current_assets float NULL,
    change_in_payables_and_accrued_expense float NULL,
    change_in_payable float NULL,
    change_in_account_payable float NULL,
    change_in_inventory float NULL,
    change_in_receivables float NULL,
    changes_in_account_receivables float NULL,
    other_non_cash_items float NULL,
    stock_based_compensation float NULL,
    deferred_tax float NULL,
    deferred_income_tax float NULL,
    depreciation_amortization_depletion float NULL,
    depreciation_and_amortization float NULL,
    net_income_from_continuing_operations float NULL,
    cash_from_discontinued_financing_activities float NULL,
    cash_from_discontinued_investing_activities float NULL,
    dividends_received_cfi float NULL,
    sale_of_business float NULL,
    capital_expenditure_reported float NULL,
    cash_from_discontinued_operating_activities float NULL,
    provisionand_write_offof_assets float NULL,
    asset_impairment_charge float NULL,
    operating_gains_losses float NULL,
    pension_and_employee_benefit_expense float NULL,
    gain_loss_on_investment_securities float NULL,
    effect_of_exchange_rate_changes float NULL,
    change_in_accrued_expense float NULL,
    change_in_tax_payable float NULL,
    change_in_income_tax_payable float NULL,
    amortization_cash_flow float NULL,
    amortization_of_intangibles float NULL,
    depreciation float NULL,
    CONSTRAINT cashflow_pkey PRIMARY KEY (ticker, report_date, frequency)
)

CREATE TABLE stocks.financials (
ticker varchar(100) NOT NULL,
insert_date date NOT NULL DEFAULT now(),
report_date date NOT NULL,
currency_code varchar(10) NULL,
frequency varchar(10) NULL,
tax_effect_of_unusual_items float NULL,
tax_rate_for_calcs float NULL,
normalized_ebitda float NULL,
net_income_from_continuing_operation_net_minority_interest float NULL,
reconciled_depreciation float NULL,
reconciled_cost_of_revenue float NULL,
ebitda float NULL,
ebit float NULL,
net_interest_income float NULL,
interest_expense float NULL,
interest_income float NULL,
normalized_income float NULL,
net_income_from_continuing_and_discontinued_operation float NULL,
total_expenses float NULL,
total_operating_income_as_reported float NULL,
diluted_average_shares float NULL,
basic_average_shares float NULL,
diluted_eps float NULL,
basic_eps float NULL,
diluted_ni_availto_com_stockholders float NULL,
net_income_common_stockholders float NULL,
net_income float NULL,
net_income_including_noncontrolling_interests float NULL,
net_income_continuous_operations float NULL,
tax_provision float NULL,
pretax_income float NULL,
other_income_expense float NULL,
other_non_operating_income_expenses float NULL,
net_non_operating_interest_income_expense float NULL,
interest_expense_non_operating float NULL,
interest_income_non_operating float NULL,
operating_income float NULL,
operating_expense float NULL,
research_and_development float NULL,
selling_general_and_administration float NULL,
gross_profit float NULL,
cost_of_revenue float NULL,
total_revenue float NULL,
operating_revenue float NULL,
CONSTRAINT financials_pkey PRIMARY KEY (ticker, report_date, frequency)
)

