# actions to be imported from https://github.com/ahnazary/actions-library repo
on:
    push:
      branches: [ master ]
    pull_request:
      branches: [ master ]

jobs:
    linters:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: ahnazary/actions-library/linting-workflows/pylint.yml@v1
            - uses: ahnazary/actions-library/linting-workflows/black.yml@v1
            - uses: ahnazary/actions-library/linting-workflows/isort.yml@v1