name: back up tables into s3

on:
  workflow_dispatch:
  schedule:
    # every first of each month at 1am
    - cron: '0 1 1 * *'



jobs:
  run-script:
    runs-on: ubuntu-latest
    environment: prod
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r finance/requirements.txt

    - name: Run finance/schedule_jobs/backup_pg_to_s3
      run: |
        echo "running backup_pg_to_s3.py"
        python finance/schedule_jobs/backup_pg_to_s3.py
      env:
        PROVIDER: ${{ secrets.PROVIDER }}
        AVN_POSTGRES_DB: ${{ secrets.AVN_POSTGRES_DB }}
        AVN_POSTGRES_USER: ${{ secrets.AVN_POSTGRES_USER }}
        AVN_POSTGRES_PASSWORD: ${{ secrets.AVN_POSTGRES_PASSWORD }}
        AVN_POSTGRES_HOST: ${{ secrets.AVN_POSTGRES_HOST }}
        AVN_POSTGRES_PORT: ${{ secrets.AVN_POSTGRES_PORT }}
        AVN_SSL_MODE: ${{ secrets.AVN_SSL_MODE }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
