name: back up tables into s3

on:
  workflow_dispatch:
  schedule:
    # every first of each month at 1am
    - cron: '0 1 1 * *'



jobs:
  run-script:
    runs-on: ubuntu-latest
    environment: prod
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r finance/requirements.txt

    - name: Run finance/schedule_jobs/backup_pg_to_s3
      run: |
        # set secrets as environment variables  
        export PROVIDER=${{ secrets.PROVIDER }}
        export NEON_POSTGRES_DB=${{ secrets.NEON_POSTGRES_DB }}
        export NEON_POSTGRES_USER=${{ secrets.NEON_POSTGRES_USER }}
        export NEON_POSTGRES_PASSWORD=${{ secrets.NEON_POSTGRES_PASSWORD }}
        export NEON_POSTGRES_HOST=${{ secrets.NEON_POSTGRES_HOST }}
        export NEON_POSTGRES_PORT=${{ secrets.NEON_POSTGRES_PORT }}
        export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
        export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
        echo "running backup_pg_to_s3.py"
        python finance/schedule_jobs/backup_pg_to_s3.py
