name: pre-deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  
jobs:
  pylint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      # if score is less than 1, the build will fail
      run: |
        pylint $(git ls-files '*.py') --fail-under=1
  
  format:
    name: Format Check
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black isort

      - name: Run black
        run: |
          black --check .
          
      - name: Run isort
        run: |
          isort . --check --diff

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r finance/requirements_tests.txt

    - name: Run PyTest
      run: |
        pytest


  sphinx-docs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    # - name: Install dependencies
    #   run: |
    #     python -m pip install --upgrade pip
    #     pip install sphinx
    #     pip install sphinx-rtd-theme

    # - name: Generate docs
    #   run: |
    #     sphinx-apidoc -o docs/source finance/
    #     cd docs/source
    #     make html

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
      with:
        publish_branch: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/build/html
        force_orphan: true
