# This workflow will install Python dependencies, run tests and lint

name: pre-deploy (linters and tests)

on:
  # run only when finance/ folder is changed
  push:
    paths:
      - 'finance/**'
    branches: [ master ]
  pull_request:
    branches: [ master ]
    paths:
      - 'finance/**'
  
jobs:
  pylint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      # if score is less than 1, the build will fail
      run: |
        pylint $(git ls-files '*.py') --fail-under=1
  
  format:
    name: Format Check
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black isort

      - name: Run black
        run: |
          black --check .
          
      - name: Run isort
        run: |
          isort --profile black --check --diff .
    
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5438:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python version
      uses: actions/setup-python@v3
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r finance/requirements_tests.txt

    - name: run pytest
      run: |
        pytest

  sqlfluff:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install sqlfluff
      run: pip install sqlfluff

    - name: Lint SQL Files
      run: sqlfluff lint $(git ls-files '*.sql') --dialect postgres