name: Run schedule jobs to update tables    

on:
  push:
    branches:
      - master

jobs:
  run-script:
    runs-on: ubuntu-latest
    environment: prod
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'
    
    - name: Check if environment variables are set
      run: |
        echo $PROVIDER
        echo $NEON_POSTGRES_PORT
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r finance/requirements.txt

    - name: Run schedule_entry.py
      run: python finance/schedule_entry.py
