name: black_test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
    black:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: run black
              uses: actions/checkout@v3
              with:
                  repository: ahnazary/actions-library
                  path: custom-actions/.github
            - name: run black
              uses: ./custom-actions/.github/workflows/black
